default_platform(:ios)

platform :ios do
  desc "Build & upload SignInPromptBlocker to TestFlight"
  lane :ci_build do
    app_identifier = "com.wildcorelabs.SignInPromptBlocker"
    app_name = "SignInPromptBlocker"
    team_id = ENV["APPLE_TEAM_ID"]

    match(
      type: "appstore",
      readonly: true,
      app_identifier: app_identifier,
      git_url: ENV["MATCH_GIT_URL"],
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"],
      team_id: team_id,
      verbose: true
    )

    proj_dir = File.expand_path("../build/#{app_name}", __dir__)
    workspace = File.join(proj_dir, "#{app_name}.xcworkspace")
    scheme = "#{app_name} (iOS)"
    archive_path = File.expand_path("../build/#{app_name}.xcarchive", __dir__)
    export_path  = File.expand_path("../build/export", __dir__)

    gym(
      workspace: workspace,
      scheme: scheme,
      configuration: "Release",
      archive_path: archive_path,
      export_method: "app-store",
      output_directory: export_path,
      output_name: "#{app_name}.ipa",
      clean: true
    )

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_IDENTIFIER"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY"]
    )
    pilot(api_key: api_key, skip_waiting_for_build_processing: true)
  end
end
